name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v2
      - run: rustup component add clippy rustfmt
      - uses: taiki-e/install-action@cargo-audit
      - run: mise run lint
      - name: Debug rg
        run: |
          which rg
          rg --version
          echo "hello world" > /tmp/rg-test.txt
          rg hello /tmp/rg-test.txt
      - run: mise x -- cargo test
      - run: cargo audit

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: jdx/mise-action@v2
      - run: rustup component add llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: mise x -- cargo llvm-cov --codecov --output-path codecov.json
      - uses: codecov/codecov-action@v5
        with:
          files: codecov.json
